# -------
# Library
# -------

library:
  name: ComposeDebugDrawer
  api: 21
  github: MFlisar/ComposeDebugDrawer
  maven: io.github.mflisar.composedebugdrawer
  maven-main-library: core
  multiplatform: false
  platforms:
    - android
  screenshots: 
    - name: core
      images:
        - ./screenshots/core/demo-theme-1.jpg
        - ./screenshots/core/demo-theme-2.jpg
        - ./screenshots/core/demo-theme-3.jpg
        - ./screenshots/core/demo2.jpg
        - ./screenshots/core/demo3.jpg
        - ./screenshots/core/demo5.jpg
        - ./screenshots/core/demo6.jpg
        - ./screenshots/core/demo7.jpg
        - ./screenshots/core/demo8.jpg
    - name: buildinfos
      images:
        - ./screenshots/buildinfos/demo1.jpg
    - name: deviceinfos
      images:
        - ./screenshots/deviceinfos/demo4.jpg
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

dependencies:
  compose-multiplatform: 1.7.1 # https://github.com/JetBrains/compose-multiplatform/releases
  jetpack-compose-runtime: 1.7.5 # https://developer.android.com/jetpack/androidx/releases/compose-runtime
  jetpack-compose-material3: 1.3.1 # https://developer.android.com/jetpack/androidx/releases/compose-material3
  experimental: false

# ------------
# Groups
# ------------

groups:
  - name: core
    label: Core
    gradle-comment: core
  - name: modules
    label: Modules
    gradle-comment: modules
  - name: plugins
    label: Plugins
    gradle-comment: plugins

# ------------
# Modules
# ------------

modules:
  - name: core
    group: core
    description: the core module - provides the basic debug drawer
    optional: false
    platforms:
      - android
    platforms-info: ""
    dependencies: []
  - name: infos-build
    group: modules
    description: provides a simple build infos region
    optional: true
    platforms:
      - android
    platforms-info: ""
    dependencies: []
  - name: infos-device
    group: modules
    description: provides a simple device infos region
    optional: true
    platforms:
      - android
    platforms-info: ""
    dependencies: []
  - name: plugin-kotpreferences
    group: plugins
    description: adds support to use KotPreferences in the debug drawer
    optional: true
    platforms:
      - android
    platforms-info: ""
    dependencies:
      - name: KotPreferences
        link: https://github.com/MFlisar/KotPreferences
        version: 0.7.2
  - name: plugin-lumberjack
    group: plugins
    description: provides a simple lumberjack region
    optional: true
    platforms:
      - android
    platforms-info: ""
    dependencies:
      - name: Lumberjack
        link: https://github.com/MFlisar/Lumberjack
        version: 7.1.2