# -------
# Library
# -------

library:
  name: ComposeDebugDrawer
  api: 21
  github: MFlisar/ComposeDebugDrawer
  maven: io.github.mflisar.composedebugdrawer
  maven-main-library: core
  multiplatform: false
  screenshots:
    - name: Drawer
      images:
        - https://raw.githubusercontent.com/MFlisar/ComposeDebugDrawer/refs/heads/main/screenshots/demo1.jpg
        - https://raw.githubusercontent.com/MFlisar/ComposeDebugDrawer/refs/heads/main/screenshots/demo3.jpg
        - https://raw.githubusercontent.com/MFlisar/ComposeDebugDrawer/refs/heads/main/screenshots/demo4.jpg
    - name: Drawer
      images:
        - https://raw.githubusercontent.com/MFlisar/ComposeDebugDrawer/refs/heads/main/screenshots/demo5.jpg
        - https://raw.githubusercontent.com/MFlisar/ComposeDebugDrawer/refs/heads/main/screenshots/demo6.jpg
        - https://raw.githubusercontent.com/MFlisar/ComposeDebugDrawer/refs/heads/main/screenshots/demo7.jpg
  branch: main
  demo: true

# ------------
# Dependencies
# ------------

# optional
dependencies:
  compose:
    cmp: 1.7.1
    compose: 1.7.5
    material3: 1.3.1
    experimental: false

# -------------
# Module
# -------------

modules:
  - name: "core"
    group: "core"
    description: "the core module that provides all theming functions"
    optional: false
    platforms:
      android: true
      ios: false
      jvm: false
      info:
    #dependencies:         # optionales Array
  - name: "infos-build"
    group: "infos"
    description: "a module to show infos about the build"
    optional: true
    platforms:
      android: true
      ios: false
      jvm: false
      info:
    #dependencies:         # optionales Array
  - name: "infos-device"
    group: "infos"
    description: "a module to show infos about the device"
    optional: true
    platforms:
      android: true
      ios: false
      jvm: false
      info:
    #dependencies:         # optionales Array
  - name: "plugin-lumberjack"
    group: "plugins"
    description: "a plugin to use my lumberjack library inside this library"
    optional: true
    platforms:
      android: true
      ios: false
      jvm: false
      info:
    dependencies: # optionales Array
      - name: Lumberjack
        link: https://mflisar.github.io/Lumberjack/
        version: 7.1.2
  - name: "plugin-kotpreferences"
    group: "plugins"
    description: "a plugin to use my kotpreferences library inside this library"
    optional: true
    platforms:
      android: true
      ios: false
      jvm: false
      info:
    dependencies: # optionales Array
    - name: KotPreferences
      link: https://mflisar.github.io/KotPreferences/
      version: 0.7.2

# GRUPPEN - optional: nur bei mehreren Modulen benötigt!
groups:
  - name: core
    label: Core
    gradle-comment: "core module"
  - name: infos
    label: Infos
    gradle-comment: "if you want to use some of the default info modules"
  - name: plugins
    label: Plugins
    gradle-comment: "plugins that add support for the corresponding libraries"