[versions]

# mflisar
lumberjack = 				"5.3.0"
kotpreferences =        	"0.3"

# ---------
# libraries
# ---------

[libraries]

# mflisar
lumberjack =			        			{ module = "com.github.MFlisar.Lumberjack:lumberjack-library", 						version.ref = "lumberjack" }
lumberjack-filelogger =	        			{ module = "com.github.MFlisar.Lumberjack:lumberjack-filelogger", 					version.ref = "lumberjack" }
lumberjack-feedback =	        			{ module = "com.github.MFlisar.Lumberjack:lumberjack-feedback", 					version.ref = "lumberjack" }
lumberjack-viewer =	            			{ module = "com.github.MFlisar.Lumberjack:lumberjack-viewer", 		    			version.ref = "lumberjack" }
lumberjack-notification =       			{ module = "com.github.MFlisar.Lumberjack:lumberjack-notification", 				version.ref = "lumberjack" }
kotpreferences-core =               		{ module = "com.github.MFlisar.KotPreferences:core", 								version.ref = "kotpreferences" }
kotpreferences-datastore =     				{ module = "com.github.MFlisar.KotPreferences:datastore",      						version.ref = "kotpreferences" }
kotpreferences-encryption-aes =     		{ module = "com.github.MFlisar.KotPreferences:encryption-aes",      				version.ref = "kotpreferences" }
kotpreferences-compose =     				{ module = "com.github.MFlisar.KotPreferences:compose",      						version.ref = "kotpreferences" }

# -------
# bundles
# -------

[bundles]